export const CLEAR_SUCCESS = 'CLEAR_SUCCESS';

// Events
export const GET_EVENTS_SUCCESS = 'GET_EVENTS_SUCCESS';
export const GET_EVENTS = 'GET_EVENTS';
export const GET_EVENT_SUCCESS = 'GET_EVENT_SUCCESS';
export const GET_EVENT = 'GET_EVENT';
export const CREATE_EVENT = 'CREATE_EVENT';
export const CREATE_EVENT_SUCCESS = 'CREATE_EVENT_SUCCESS';
export const CLEAR_CREATE_EVENT_FLAGS = 'CLEAR_CREATE_EVENT_FLAGS';
export const DELETE_EVENT = 'DELETE_EVENT';
export const SET_CURRENT = 'SET_CURRENT';
export const CLEAR_CURRENT = 'CLEAR_CURRENT';
export const UPDATE_EVENT_SUCCESS = 'UPDATE_EVENT_SUCCESS';
export const UPDATE_EVENT = 'UPDATE_EVENT';
export const FILTER_EVENTS = 'FILTER_EVENTS';
export const CLEAR_EVENTS = 'CLEAR_EVENTS';
export const CLEAR_FILTER = 'CLEAR_FILTER';
export const CREATE_EVENT_ERROR = 'CREATE_EVENT_ERROR';
export const GET_EVENTS_ERROR = 'GET_EVENTS_ERROR';
export const DELETE_EVENT_ERROR = 'DELETE_EVENT_ERROR';
export const UPDATE_EVENT_ERROR = 'UPDATE_EVENT_ERROR';
export const LOAD_EVENT = 'LOAD_EVENT';
export const LOAD_EVENT_SUCCESS = 'LOAD_EVENT_SUCCESS';
export const LOAD_EVENT_ERROR = 'LOAD_EVENT_ERROR';
export const ADD_SELF_TO_EVENT = 'ADD_SELF_TO_EVENT';

// Alerts
export const SET_ALERT = 'SET_ALERT';
export const REMOVE_ALERT = 'REMOVE_ALERT';
//Auth
export const SIGNUP_SUCCESS = 'SIGNUP_SUCCESS';
export const SIGNUP_FAIL = 'SIGNUP_FAIL';
export const USER_LOADED = 'USER_LOADED';
export const AUTH_ERROR = 'AUTH_ERROR';
export const LOGIN_SUCCESS = 'LOGIN_SUCCESS';
export const LOGIN_FAIL = 'LOGIN_FAIL';
export const LOGOUT = 'LOGOUT';
export const CLEAR_ERRORS = 'CLEAR_ERRORS';
export const UPDATE_PROFILE_SUCCESS = 'UPDATE_PROFILE_SUCCESS';
export const UPDATE_PROFILE_FAIL = 'UPDATE_PROFILE_FAIL';
export const FORGOT_PASSWORD_SUCCESS = 'FORGOT_PASSWORD_SUCCESS';
export const RESET_PASSWORD_SUCCESS = 'RESET_PASSWORD_SUCCESS';
export const RESET_PASSWORD_FAIL = 'RESET_PASSWORD_FAIL';
export const FORGOT_RESET_SUCCESS = 'FORGOT_RESET_SUCCESS';
export const FORGOT_RESET_FAIL = 'FORGOT_RESET_FAIL';
// Locations
export const GET_LOCATIONS = 'GET_LOCATIONS';
export const ADD_LOCATION = 'ADD_LOCATION';
export const DELETE_LOCATION = 'DELETE_LOCATION';
export const UPDATE_LOCATION = 'UPDATE_LOCATION';
export const FILTER_LOCATIONS = 'FILTER_LOCATIONS';
export const CLEAR_LOCATIONS = 'CLEAR_LOCATIONS';
export const LOCATION_ERROR = 'LOCATION_ERROR';
// Languages
export const GET_LANGUAGES = 'GET_LANGUAGES';
export const ADD_LANGUAGE = 'ADD_LANGUAGE';
export const DELETE_LANGUAGE = 'DELETE_LANGUAGE';
export const UPDATE_LANGUAGE = 'UPDATE_LANGUAGE';
export const FILTER_LANGUAGES = 'FILTER_LANGUAGES';
export const CLEAR_LANGUAGES = 'CLEAR_LANGUAGES';
export const LANGUAGE_ERROR = 'LANGUAGE_ERROR';
// Jobs
export const GET_JOBS_SUCCESS = 'GET_JOBS_SUCCESS';
export const GET_JOBS = 'GET_JOBS';
export const GET_JOB_SUCCESS = 'GET_JOB_SUCCESS';
export const GET_JOB = 'GET_JOB';
export const CREATE_JOB = 'CREATE_JOB';
export const CREATE_JOB_SUCCESS = 'CREATE_JOB_SUCCESS';
export const CLEAR_CREATE_JOB_FLAGS = 'CLEAR_CREATE_JOB_FLAGS';
export const SET_CURRENT = 'SET_CURRENT';
export const CLEAR_CURRENT = 'CLEAR_CURRENT';
export const UPDATE_JOB_SUCCESS = 'UPDATE_JOB_SUCCESS';
export const UPDATE_JOB = 'UPDATE_JOB';
export const FILTER_JOBS = 'FILTER_JOBS';
export const CLEAR_JOBS = 'CLEAR_JOBS';
export const CLEAR_JOB_FILTER = 'CLEAR_JOB_FILTER';
export const CREATE_JOB_ERROR = 'CREATE_JOB_ERROR';
export const GET_JOBS_ERROR = 'GET_JOBS_ERROR';
export const DELETE_JOB_ERROR = 'DELETE_JOB_ERROR';
export const UPDATE_JOB_ERROR = 'UPDATE_JOB_ERROR';
